language: python
python: 3.4
cache:
  directories:
    - ~/.cache/pip
sudo: false
install:
  # Build development/test dependencies.
  - pip install -U pip wheel
  - pip install -r requirements-dev.txt
script: py.test
